name: Deploy to OSS

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
       # with:
       #   submodules: true

      #- name: Deploy to GitHub
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    personal_token: ${{ secrets.personal_token }}
      #    external_repository: eallion/favorite
      #    PUBLISH_BRANCH: gh-pages
      #    PUBLISH_DIR: ./
      #    allow_empty_commit: true
      #    commit_message: ${{ GitHub.event.head_commit.message }}

      # 部署到阿里云 OSS
      #- name: Deploy to OSS
      #  uses: saltbo/uptoc@master
      #  with:
      #    driver: oss
      #    region: cn-shanghai
      #    bucket: ${{ secrets.bucket }}
      #    exclude: .git,.github
      #    dist: ./
      #  env:
      #    UPTOC_UPLOADER_AK: ${{ secrets.ACCESS_KEY_ID }}
      #    UPTOC_UPLOADER_SK: ${{ secrets.ACCESS_KEY_SECRET }}

      # 部署到腾讯云 COS
      #- name: Deploy to COS
      #  uses: saltbo/uptoc@master
      #  with:
      #    driver: cos
      #    region: ap-shanghai
      #    bucket: ${{ secrets.COS_BUCKET }}
      #    exclude: .git,.github
      #    dist: ./
      #  env:
      #    UPTOC_UPLOADER_AK: ${{ secrets.COS_ACCESS_KEY_ID }}
      #    UPTOC_UPLOADER_SK: ${{ secrets.COS_ACCESS_KEY_SECRET }}